default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: projeto_tcc_development

test:
  <<: *default
  database: projeto_tcc_test

production:
  <<: *default
  database: projeto_tcc_production
  username: projeto_tcc
  password: <%= ENV['PROJETO_TCC_DATABASE_PASSWORD'] %>
